//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public Alumno()
        {
            this.DatosAlumno = new HashSet<DatosAlumno>();
        }
    
        public int idAlumno { get; set; }
        public string nombre { get; set; }
        public int idCurso { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual ICollection<DatosAlumno> DatosAlumno { get; set; }
    }
}
