//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosAlumno
    {
        public int idDatosPersonales { get; set; }
        public string apellidos { get; set; }
        public int edad { get; set; }
        public int idAlumno { get; set; }
    
        public virtual Alumno Alumno { get; set; }
    }
}
